sudo: required
language: python
python: 3.8
services:
  - docker

before_install:
  # install heroku CLI
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
  # login to docker registries (dockerhub + heroku)
  - heroku container:login

script:
  - heroku container:push web

deploy:
  provider: script
  script:
    heroku container:release web --app $HEROKU_APPNAME
  on:
    branch: devel