version: "3.6"

services:
  user-service:
    build: .
    image: paxapp/pax-user:latest
    volumes:
      - ".:/app"
    ports:
      - 5001:5000
    environment:
      - FLASK_APP=project/__init__.py
      - FLASK_ENV=production
      - APP_SETTINGS=project.config.ProductionConfig
