version: "3.6"

services:
  user-service:
    build:
    context: ./services/user
    dockerfile: Dockerfile
    volumes:
      - "./services/user:/usr/src/app"
    ports:
      - 5001:5000
    environment:
      - FLASK_APP=project/__init
