version: "3.6"

services:
  user-service:
    build: .
    image: paxapp/pax-user:latest
    volumes:
      - ".:/app"
    ports:
      - 5001:5000
    environment:
      - FLASK_APP=project/__init__.py
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=mysql+pymysql://f15jto2ojbvbb18m:ojjbjm6lswedzs91@bqmayq5x95g1sgr9.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/j3uyakutbdjh3tdy
      - DATABASE_TEST_URL=mysql+pymysql://username:password@localhost:3306/pax
      - SECRET_KEY=my_precious
